server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url:
    username:
    password:
    driver-class-name:
  threads:
    virtual:
      enabled: true

jwt:
  secretkey: 91e916ff658fade69312c1c2177850ca2d1f1e5aa50a117c94ca50619ef4d003
  audience: booktrading
  issuer: abs
