server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 123456
    url: jdbc:postgresql://localhost:5432/ShippingDB
  jpa:
    hibernate:
      ddl-auto: update


kafka:
  bootstrap-servers: localhost:9092
  topics:
    user:
      shipping: send-shipping-mail

