server:
  port: 8081
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: aybuke
      password: root
      database: ListDB

kafka:
  bootstrap-servers: localhost:9092
  topics:
    user:
      exchange-list : send-exchange-list-mail
      sale-list : send-sale-list-mail

