server:
  port: 8081
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: aybuke
      password: root
      database: ListDB

recommendation:
  url: http://localhost:8000/recommend


